version: 2.1
orbs:
  release-management: salesforce/npm-release-management@4
workflows:
  test-and-release:
    when:
      equal: [test-and-release, << pipeline.parameters.workflow >>]
    jobs:
      - release-management/validate-pr:
          filters:
            branches:
              ignore: main
      - release-management/test-package:
          matrix:
            parameters:
              os:
                - linux
                - windows
              node_version:
                - latest
                - lts
                - maintenance
      - release-management/test-nut:
          matrix:
            parameters:
              os:
                - linux
                - windows
              sfdx_version:
                - latest
              node_version:
                - latest
          requires:
            - release-management/test-package
      - release-management/release-package:
          context:
            - AWS
            - release
          sign: true
          github-release: true
          requires:
            - release-management/test-package
          filters:
            branches:
              only: main
  test-ts-update:
    when:
      equal: [test-ts-update, << pipeline.parameters.workflow >>]
    jobs:
      - release-management/test-ts-update
  dependabot-automerge:
    when:
      equal: [dependabot-automerge, << pipeline.parameters.workflow >>]
    jobs:
      - release-management/dependabot-automerge:
          context: release
parameters:
  workflow:
    description: |
      String that controls which workflow would run.

      This parameter is used by automation to determine if a workflow will run
      within a pipeline.
    type: string
    default: 'test-and-release'
